<?php
require_once __DIR__ . '/../auth/guard.php';
require_once __DIR__ . '/../auth/db.php';
guardRole('employee');
$db  = getDB();
$uid = $_SESSION['user_id'];

$payslips = $db->prepare("
    SELECT * FROM payslips WHERE user_id = ? ORDER BY year DESC, month DESC
");
$payslips->execute([$uid]);
$payslips = $payslips->fetchAll();
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>My Payslips – HRMS Portal</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../assets/style.css">
</head>
<body>
<div class="app-shell">
<?php include __DIR__ . '/sidebar.php'; ?>
<div class="main-content">

  <header class="topbar">
    <div class="topbar-left">
      <span class="page-title">My Payslips</span>
      <span class="page-breadcrumb">Monthly salary slips</span>
    </div>
    <div class="topbar-right">
      <span class="role-chip">Employee</span>
      <div class="topbar-avatar"><?= strtoupper(substr($_SESSION['user_name'],0,1)) ?></div>
      <span class="topbar-name"><?= htmlspecialchars($_SESSION['user_name']) ?></span>
    </div>
  </header>

  <div class="page-body">

    <?php if(empty($payslips)): ?>
      <div class="card"><div class="card-body" style="text-align:center;padding:60px 20px;">
        <div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:6px;">No payslips yet</div>
        <div style="font-size:13px;color:var(--muted);">Your payslips will appear here once generated by admin.</div>
      </div></div>
    <?php else: ?>
    <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px;">
      <?php foreach($payslips as $ps): ?>
      <a href="../admin/view_payslip.php?id=<?= $ps['id'] ?>" style="text-decoration:none;">
        <div class="card" style="padding:18px 20px;transition:all .15s;cursor:pointer;" onmouseover="this.style.borderColor='var(--brand)'" onmouseout="this.style.borderColor=''">
          <div style="font-size:16px;font-weight:800;color:var(--text);margin-bottom:4px;"><?= date('F Y', mktime(0,0,0,$ps['month'],1,$ps['year'])) ?></div>
          <div style="display:flex;justify-content:space-between;margin-top:10px;">
            <div><div style="font-size:11px;color:var(--muted);">Earnings</div><div style="font-size:14px;font-weight:700;color:var(--green-text);">₹<?= number_format($ps['total_earnings'],0) ?></div></div>
            <div><div style="font-size:11px;color:var(--muted);">Deductions</div><div style="font-size:14px;font-weight:700;color:var(--red);">₹<?= number_format($ps['total_deductions'],0) ?></div></div>
            <div><div style="font-size:11px;color:var(--muted);">Net Pay</div><div style="font-size:14px;font-weight:800;color:var(--brand);">₹<?= number_format($ps['net_payable'],0) ?></div></div>
          </div>
        </div>
      </a>
      <?php endforeach; ?>
    </div>
    <?php endif; ?>

  </div>
</div>
</div>
</body>
</html>
