<?php
require_once __DIR__ . '/../auth/guard.php';
require_once __DIR__ . '/../auth/db.php';
guardRole('employee');
$db  = getDB();
$uid = $_SESSION['user_id'];

$filterYear = (int)($_GET['year'] ?? date('Y'));

$payslips = $db->prepare("SELECT * FROM payslips WHERE user_id=? AND year=? ORDER BY month DESC");
$payslips->execute([$uid, $filterYear]);
$payslips = $payslips->fetchAll();

$years = $db->prepare("SELECT DISTINCT year FROM payslips WHERE user_id=? ORDER BY year DESC");
$years->execute([$uid]);
$years = $years->fetchAll(PDO::FETCH_COLUMN);
if (!in_array($filterYear, $years)) $years[] = $filterYear;
sort($years);
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>My Payslips – HRMS Portal</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../assets/style.css">
</head>
<body>
<div class="app-shell">
<?php include __DIR__ . '/sidebar.php'; ?>
<div class="main-content">

  <header class="topbar">
    <div class="topbar-left">
      <span class="page-title">My Payslips</span>
      <span class="page-breadcrumb"><?= $filterYear ?></span>
    </div>
    <div class="topbar-right">
      <span class="role-chip">Employee</span>
      <div class="topbar-avatar"><?= strtoupper(substr($_SESSION['user_name'],0,1)) ?></div>
      <span class="topbar-name"><?= htmlspecialchars($_SESSION['user_name']) ?></span>
    </div>
  </header>

  <div class="page-body">

    <!-- Filter -->
    <form method="GET" style="display:flex;gap:10px;margin-bottom:20px;align-items:center;">
      <select name="year" class="form-control" style="font-size:13px;padding:9px 12px;width:auto;" onchange="this.form.submit()">
        <?php foreach($years as $y): ?>
          <option value="<?= $y ?>" <?= $y==$filterYear?'selected':'' ?>><?= $y ?></option>
        <?php endforeach; ?>
      </select>
      <span style="font-size:13px;color:var(--muted);"><?= count($payslips) ?> payslip(s)</span>
    </form>

    <!-- Table -->
    <?php if(empty($payslips)): ?>
      <div class="card"><div class="card-body" style="text-align:center;padding:60px 20px;">
        <div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:6px;">No payslips for <?= $filterYear ?></div>
        <div style="font-size:13px;color:var(--muted);">Your payslips will appear here once generated by admin.</div>
      </div></div>
    <?php else: ?>
    <div class="table-wrap">
      <div class="table-toolbar"><h2>Payslips — <?= $filterYear ?></h2></div>
      <table>
        <thead>
          <tr>
            <th>Month</th>
            <th style="text-align:center;">Gross (Annual)</th>
            <th style="text-align:center;">Earnings</th>
            <th style="text-align:center;">Deductions</th>
            <th style="text-align:center;">Net Payable</th>
            <th style="text-align:center;">Days</th>
            <th style="width:70px;"></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach($payslips as $ps): ?>
          <tr>
            <td class="font-semibold"><?= date('F', mktime(0,0,0,$ps['month'],1)) ?></td>
            <td style="text-align:center;color:var(--muted);">₹<?= number_format($ps['gross_salary'],0) ?></td>
            <td style="text-align:center;font-weight:700;color:var(--green-text);">₹<?= number_format($ps['total_earnings'],0) ?></td>
            <td style="text-align:center;font-weight:700;color:var(--red);">₹<?= number_format($ps['total_deductions'] + ($ps['total_employer_cost']??0),0) ?></td>
            <td style="text-align:center;font-weight:800;color:var(--brand);">₹<?= number_format($ps['net_payable'],0) ?></td>
            <td style="text-align:center;color:var(--muted);"><?= (int)($ps['days_payable']??0) ?></td>
            <td><a href="../admin/view_payslip.php?id=<?= $ps['id'] ?>" class="btn btn-sm" style="background:var(--brand-light);color:var(--brand);border:1px solid #c7d2fe;">View</a></td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
    <?php endif; ?>

  </div>
</div>
</div>
</body>
</html>
